### ISSUE TITLE
create bash scripts

### ISSUE THREAD

**Issue by muddlebee** [nb2998/Revise-git#1]
Why not scripts ? 
https://github.com/jwiegley/git-scripts

**Comment by nb2998** [comment]
@anweshknayak Oh thank you so much for the insight! But as I am not an expert in git yet, I prefer to write commands to have a better knowledge of what each command actually does (and learn from the blunders I make, I make many!). :)

**Comment by muddlebee** [comment]
@nb2998 keep hacking. long way to go. :tada:
